### ISSUE TITLE
Exception in plugin, WebStorm 2017.2.4

### ISSUE THREAD

**Issue by localpcguy** [Turbo87/intellij-emberjs#160]
Got an exception in WebStorm, error message: `it must not be null`

> WebStorm 2017.2.4
> Build #WS-172.4155.35

Stack trace from WebStorm below:

```it must not be null
java.lang.IllegalStateException: it must not be null
	at com.emberjs.index.EmberNameIndex$Companion$getFilteredKeys$filter$1.value(EmberNameIndex.kt:49)
	at com.emberjs.index.EmberNameIndex$Companion$getFilteredKeys$filter$1.value(EmberNameIndex.kt:26)
	at com.intellij.util.FilteringProcessor.process(FilteringProcessor.java:34)
	at com.intellij.util.io.AppendableStorageBackedByResizableMappedFile.processAll(AppendableStorageBackedByResizableMappedFile.java:135)
	at com.intellij.util.io.PersistentEnumeratorBase.iterateData(PersistentEnumeratorBase.java:456)
	at com.intellij.util.io.PersistentHashMap.processKeys(PersistentHashMap.java:478)
	at com.intellij.util.indexing.VfsAwareMapIndexStorage.processKeys(VfsAwareMapIndexStorage.java:207)
	at com.intellij.util.indexing.MemoryIndexStorage.processKeys(MemoryIndexStorage.java:151)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.processAllKeys(VfsAwareMapReduceIndex.java:157)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:610)
	at com.emberjs.index.EmberNameIndex$Companion.processAllKeys(EmberNameIndex.kt:36)
	at com.emberjs.index.EmberNameIndex$Companion.processAllKeys$default(EmberNameIndex.kt:35)
	at com.emberjs.index.EmberNameIndex$Companion.getFilteredKeys(EmberNameIndex.kt:51)
	at com.emberjs.psi.EmberJSLiteralReference.resolve(EmberJSLiteralReference.kt:33)
	at com.emberjs.psi.EmberJSLiteralReference.multiResolve(EmberJSLiteralReference.kt:26)
	at com.intellij.psi.PsiPolyVariantReferenceBase.isReferenceTo(PsiPolyVariantReferenceBase.java:52)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:52)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.lambda$execute$0(PsiSearchHelperImpl.java:754)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:138)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:225)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.execute(PsiSearchHelperImpl.java:750)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:247)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:238)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processCandidates$13(PsiSearchHelperImpl.java:712)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$5(PsiSearchHelperImpl.java:421)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:40)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:405)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$2(PsiSearchHelperImpl.java:323)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$3(PsiSearchHelperImpl.java:351)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Turbo87** [comment]
thanks! any idea what might have triggered this or how to reproduce it?

**Comment by localpcguy** [comment]
I just upgraded WebStorm, and it started throwing that error. It was happening consistently anytime I closed and re-opened WebStorm. However, I've tried 2 different Ember apps now and it's no longer happening. I'll see if I can reproduce and let you know.

**Comment by localpcguy** [comment]
I have not seen this again - I'm going to chalk it up to weirdness right after the update that one of the restarts (or maybe one of the other plugin updates) resolved. I'll re-open if it re-occurs and I can pin it down.

**Comment by Turbo87** [comment]
okay, thanks!
