### ISSUE TITLE
null cannot be cast to non-null type kotlin.String

### ISSUE THREAD

**Issue by Turbo87** [Turbo87/intellij-emberjs#180]
```
null cannot be cast to non-null type kotlin.String
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
	at com.emberjs.folding.EmberGetFoldingBuilder$buildFoldRegions$1.visitJSCallExpression(EmberGetFoldingBuilder.kt:41)
	at com.intellij.lang.javascript.psi.impl.JSCallExpressionImpl.accept(JSCallExpressionImpl.java:100)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSArgumentList(JSElementVisitor.java:192)
	at com.intellij.lang.javascript.psi.impl.JSArgumentListImpl.accept(JSArgumentListImpl.java:57)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSExpression(JSElementVisitor.java:226)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSCallExpression(JSElementVisitor.java:34)
	at com.emberjs.folding.EmberGetFoldingBuilder$buildFoldRegions$1.visitJSCallExpression(EmberGetFoldingBuilder.kt:24)
	at com.intellij.lang.javascript.psi.impl.JSCallExpressionImpl.accept(JSCallExpressionImpl.java:100)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSVariable(JSElementVisitor.java:200)
	at com.intellij.lang.javascript.psi.impl.JSVariableBaseImpl.accept(JSVariableBaseImpl.java:395)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSSourceElement(JSElementVisitor.java:212)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSStatement(JSElementVisitor.java:222)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSVarStatement(JSElementVisitor.java:176)
	at com.intellij.lang.javascript.psi.impl.JSVarStatementBase.accept(JSVarStatementBase.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSSourceElement(JSElementVisitor.java:212)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSStatement(JSElementVisitor.java:222)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSBlock(JSElementVisitor.java:188)
	at com.intellij.lang.javascript.psi.impl.JSBlockStatementImpl.accept(JSBlockStatementImpl.java:55)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSProperty(JSElementVisitor.java:80)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitES6FunctionProperty(JSElementVisitor.java:484)
	at com.intellij.lang.ecmascript6.psi.impl.ES6FunctionPropertyImpl.accept(ES6FunctionPropertyImpl.java:47)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSExpression(JSElementVisitor.java:226)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSObjectLiteralExpression(JSElementVisitor.java:84)
	at com.intellij.lang.javascript.psi.impl.JSObjectLiteralExpressionImpl.accept(JSObjectLiteralExpressionImpl.java:89)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSArgumentList(JSElementVisitor.java:192)
	at com.intellij.lang.javascript.psi.impl.JSArgumentListImpl.accept(JSArgumentListImpl.java:57)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSExpression(JSElementVisitor.java:226)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSCallExpression(JSElementVisitor.java:34)
	at com.emberjs.folding.EmberGetFoldingBuilder$buildFoldRegions$1.visitJSCallExpression(EmberGetFoldingBuilder.kt:24)
	at com.intellij.lang.javascript.psi.impl.JSCallExpressionImpl.accept(JSCallExpressionImpl.java:100)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:13)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:208)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSSourceElement(JSElementVisitor.java:212)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSStatement(JSElementVisitor.java:222)
	at com.intellij.lang.javascript.psi.JSElementVisitor.visitES6ExportDefaultAssignment(JSElementVisitor.java:459)
	at com.intellij.lang.ecmascript6.psi.impl.ES6ExportDefaultAssignmentImpl.accept(ES6ExportDefaultAssignmentImpl.java:59)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:823)
	at com.emberjs.folding.EmberGetFoldingBuilder.buildFoldRegions(EmberGetFoldingBuilder.kt:22)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:97)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:238)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:224)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:109)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:98)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:94)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.a(CodeFoldingManagerImpl.java:319)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:305)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Turbo87** [comment]
this was using code from https://github.com/Turbo87/intellij-emberjs/pull/173, which was not merged, so this issue is now irrelevant
