### ISSUE TITLE
String index out of range: 12

### ISSUE THREAD

**Issue by shofmannka** [Turbo87/intellij-emberjs#182]
I have received the following bug, see below. The error message occurred after stating WebStorm and loading my Ember project. 
Best regards Stefan

String index out of range: 12
java.lang.StringIndexOutOfBoundsException: String index out of range: 12
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.subSequence(AbstractStringBuilder.java:912)
	at java.lang.StringBuilder.subSequence(StringBuilder.java:76)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.reparse(FileReferenceSet.java:264)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.reparse(FileReferenceSet.java:212)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.<init>(FileReferenceSet.java:99)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.<init>(FileReferenceSet.java:77)
	at com.emberjs.resolver.EmberModuleReferenceContributor$getAllReferences$refs$1.<init>(EmberModuleReferenceContributor.kt:61)
	at com.emberjs.resolver.EmberModuleReferenceContributor.getAllReferences(EmberModuleReferenceContributor.kt:61)
	at com.intellij.lang.javascript.psi.resolve.JSModuleReferenceContributor.getReferences(JSModuleReferenceContributor.java:132)
	at com.intellij.lang.javascript.frameworks.amd.JSAmdReferenceContributor$1.getReferencesByElement(JSAmdReferenceContributor.java:85)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:59)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:53)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.createRefs(JSLiteralExpressionImpl.java:91)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.access$000(JSLiteralExpressionImpl.java:47)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl$1.compute(JSLiteralExpressionImpl.java:74)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl$1.compute(JSLiteralExpressionImpl.java:70)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.getReferences(JSLiteralExpressionImpl.java:81)
	at com.intellij.lang.javascript.inspections.JSFileReferencesInspection$1.checkReferences(JSFileReferencesInspection.java:99)
	at com.intellij.lang.javascript.inspections.JSFileReferencesInspection$1.visitJSLiteralExpression(JSFileReferencesInspection.java:88)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.accept(JSLiteralExpressionImpl.java:111)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by Turbo87** [comment]
this seems to be the same as https://github.com/Turbo87/intellij-emberjs/issues/176
