### ISSUE TITLE
Errors after update to 2018.1 

### ISSUE THREAD

**Issue by vlascik** [Turbo87/intellij-emberjs#187]
Seems that these happen in non-js projects (php in this case), but break things like highlighting in js/ts projects too. Worked fine in 2017.3 right before the update.

Error while indexing \\ 
or 
Error while indexing P:\Project\something.php
```
To reindex this file IDEA has to be restarted: containingFile.originalFile.virtualFile must not be null
java.lang.IllegalStateException: containingFile.originalFile.virtualFile must not be null
	at com.emberjs.utils.PsiElementExtensionsKt.getOriginalVirtualFile(PsiElementExtensions.kt:13)
	at com.emberjs.navigation.EmberTestFinder.isTest(EmberTestFinder.kt:55)
	at com.intellij.testIntegration.TestFinderHelper.isTest(TestFinderHelper.java:59)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpUnitCoversIndex$1.map(PhpUnitCoversIndex.java:61)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpUnitCoversIndex$1.map(PhpUnitCoversIndex.java:52)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:273)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:98)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:213)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1646)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$19(FileBasedIndexImpl.java:1574)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:523)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1533)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1517)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1500)
	at com.intellij.util.indexing.FileBasedIndexProjectHandler.lambda$reindexRefreshedFiles$2(FileBasedIndexProjectHandler.java:190)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:230)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:243)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Turbo87** [comment]
Are you using IntelliJ itself or some other version like Webstorm, etc?

**Comment by vlascik** [comment]
IntelliJ

**Comment by vlascik** [comment]
The errors show up immediately after you install the PHP plugin, I imagine it will happen with PHPStorm and others as well.
The problem seems to be that this returns null on PHP files (some are included in that plugin):
```
// src\main\kotlin\com\emberjs\utils\PsiElementExtensions.kt
val PsiElement.originalVirtualFile: VirtualFile
    get() = containingFile.originalFile.virtualFile
```
called from 
```
// com/emberjs/navigation/EmberTestFinder.kt
    override fun isTest(element: PsiElement): Boolean {
        val file = element.originalVirtualFile
```
I managed to build the plugin, but I don't know why ember is processing PHP files in the first place, most breakpoints don't work for me, kotlin is just not that intuitive, and I just can't fix it in a reasonable timeframe.

**Comment by localpcguy** [comment]
Can verify this happens in PHPStorm as well after updating to the 2018.1 version

same error as what is listed above (just with a different PHP filename)

**Comment by Turbo87** [comment]
what version of the plugin are you running in 2018.1?

**Comment by localpcguy** [comment]
Started seeing the issues after updating to `v2018.1.1-0` version of the plugin. Prior to updating it had gotten disabled upon updating PHPStorm to `2018.1.x`

**Comment by Turbo87** [comment]
hmm okay, thanks

**Comment by thewulf00** [comment]
@Turbo87 So do you think, you can deliver a solution? I am having this exception multiple times every day :-(
