### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MR-H0200** [Turbo87/intellij-emberjs#229]
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 9
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.subSequence(AbstractStringBuilder.java:912)
	at java.lang.StringBuilder.subSequence(StringBuilder.java:76)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.reparse(FileReferenceSet.java:264)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.reparse(FileReferenceSet.java:212)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.<init>(FileReferenceSet.java:99)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.<init>(FileReferenceSet.java:77)
	at com.emberjs.resolver.EmberModuleReferenceContributor$getAllReferences$refs$1.<init>(EmberModuleReferenceContributor.kt:61)
	at com.emberjs.resolver.EmberModuleReferenceContributor.getAllReferences(EmberModuleReferenceContributor.kt:61)
	at com.intellij.lang.javascript.psi.resolve.JSModuleReferenceContributor.getReferences(JSModuleReferenceContributor.java:133)
	at com.intellij.lang.javascript.frameworks.amd.JSAmdReferenceContributor$1.getReferencesByElement(JSAmdReferenceContributor.java:84)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:50)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:44)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.createRefs(JSLiteralExpressionImpl.java:93)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.access$000(JSLiteralExpressionImpl.java:48)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl$1.compute(JSLiteralExpressionImpl.java:76)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl$1.compute(JSLiteralExpressionImpl.java:72)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.getReferences(JSLiteralExpressionImpl.java:83)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.checkReferences(JSAnnotatingVisitor.java:237)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.checkReferences(JSAnnotatingVisitor.java:228)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.visitJSLiteralExpression(JSAnnotatingVisitor.java:150)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.accept(JSLiteralExpressionImpl.java:113)
	at com.intellij.lang.javascript.validation.JSAnnotator.annotate(JSAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:366)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by makepanic** [comment]
Can you maybe provide additional information on this error?

* your intellij version
* your ember-intellij version
* a short description on when this error appeared

@Turbo87 would you be interested in creating an issue template to possibly improve issue creation?

**Comment by harip0200** [comment]
intellij version 2018.2

I am having a generated js file with  **16071** characters long.

while opening that file got this error

**Comment by cah-briangantzler** [comment]
I also get this error. Many times over the last few updates of intellij, so it doesnt appear to any specific version. I notice the blinking event log and I see the error. I have no idea when it showed up to know what I was doing that may have triggered it. It doesnt appear to stop anything in the plugin. So far I have just been ignoring them.

I was hoping that the stack trace would give some kind of idea as to what the plugin was trying to do. I see that my stack trace appears to be the same functions as the above stack trace.

java.lang.StringIndexOutOfBoundsException: String index out of range: 24
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.subSequence(AbstractStringBuilder.java:912)
	at java.lang.StringBuilder.subSequence(StringBuilder.java:76)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.reparse(FileReferenceSet.java:264)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.reparse(FileReferenceSet.java:212)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.<init>(FileReferenceSet.java:99)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.<init>(FileReferenceSet.java:77)
	at com.emberjs.resolver.EmberModuleReferenceContributor$getAllReferences$refs$1.<init>(EmberModuleReferenceContributor.kt:61)
	at com.emberjs.resolver.EmberModuleReferenceContributor.getAllReferences(EmberModuleReferenceContributor.kt:61)
	at com.intellij.lang.javascript.psi.resolve.JSModuleReferenceContributor.getReferences(JSModuleReferenceContributor.java:133)
	at com.intellij.lang.javascript.frameworks.amd.JSAmdReferenceContributor$1.getReferencesByElement(JSAmdReferenceContributor.java:84)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:50)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:44)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.createRefs(JSLiteralExpressionImpl.java:93)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.access$000(JSLiteralExpressionImpl.java:48)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl$1.compute(JSLiteralExpressionImpl.java:76)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl$1.compute(JSLiteralExpressionImpl.java:72)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.getReferences(JSLiteralExpressionImpl.java:83)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectedReferences(InjectedReferencesContributor.java:55)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesInspection$1.visitElement(InjectedReferencesInspection.java:39)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.accept(JSLiteralExpressionImpl.java:116)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$4(LocalInspectionsPass.java:299)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:223)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:151)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:223)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by ControlTheBit** [comment]
Same error here... :-)

**IntelliJ Version:**
```
IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
macOS 10.14.2
```
**Ember Plugin Version:** `v2018.3.1-0`
**What I did:** I opened the file `dist/assets/[project]-ember.js` after executing `ember build` in the console

Stacktrace:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 11
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.subSequence(AbstractStringBuilder.java:912)
	at java.lang.StringBuilder.subSequence(StringBuilder.java:76)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.reparse(FileReferenceSet.java:268)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.reparse(FileReferenceSet.java:213)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.<init>(FileReferenceSet.java:99)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet.<init>(FileReferenceSet.java:77)
	at com.emberjs.resolver.EmberModuleReferenceContributor$getAllReferences$refs$1.<init>(EmberModuleReferenceContributor.kt:61)
	at com.emberjs.resolver.EmberModuleReferenceContributor.getAllReferences(EmberModuleReferenceContributor.kt:61)
	at com.intellij.lang.javascript.psi.resolve.JSModuleReferenceContributor.getReferences(JSModuleReferenceContributor.java:133)
	at com.intellij.lang.javascript.frameworks.amd.JSAmdReferenceContributor$1.getReferencesByElement(JSAmdReferenceContributor.java:86)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:50)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:44)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.createRefs(JSLiteralExpressionImpl.java:95)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.access$000(JSLiteralExpressionImpl.java:49)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl$1.compute(JSLiteralExpressionImpl.java:77)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl$1.compute(JSLiteralExpressionImpl.java:73)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.getReferences(JSLiteralExpressionImpl.java:85)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromAmdModuleReference(JSTypeEvaluator.java:1762)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptTypeEvaluator.addTypeFromAmdModuleReference(TypeScriptTypeEvaluator.java:722)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromVariableResolveResult(JSTypeEvaluator.java:1525)
	at com.intellij.lang.ecmascript6.resolve.ES6TypeEvaluator.addTypeFromVariableResolveResult(ES6TypeEvaluator.java:113)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptTypeEvaluator.addTypeFromVariableResolveResult(TypeScriptTypeEvaluator.java:311)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromResolveResult(JSTypeEvaluator.java:1507)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$processRefExpr$30(JSTypeEvaluator.java:1446)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluateContext.processExpression(JSEvaluateContext.java:197)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processRefExpr(JSTypeEvaluator.java:1437)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateTypes(JSTypeEvaluator.java:502)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateExpressionOrElementTypes(JSTypeEvaluator.java:158)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$evaluateExpressionOrElementTypes$1(JSTypeEvaluator.java:141)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processWithEvaluationGuard(JSTypeEvaluator.java:2740)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateExpressionOrElementTypes(JSTypeEvaluator.java:141)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:133)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:116)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:32)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:2201)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:466)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.getResolveResultsFromQualifier(JSTypeEvaluator.java:1483)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptTypeEvaluator.getResolveResultsFromQualifier(TypeScriptTypeEvaluator.java:585)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$processRefExpr$30(JSTypeEvaluator.java:1439)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluateContext.processExpression(JSEvaluateContext.java:197)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processRefExpr(JSTypeEvaluator.java:1437)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateTypes(JSTypeEvaluator.java:502)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateExpressionOrElementTypes(JSTypeEvaluator.java:158)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$evaluateExpressionOrElementTypes$1(JSTypeEvaluator.java:141)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processWithEvaluationGuard(JSTypeEvaluator.java:2740)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateExpressionOrElementTypes(JSTypeEvaluator.java:141)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:133)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:116)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:32)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:2201)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:466)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.getResolveResultsFromQualifier(JSTypeEvaluator.java:1483)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptTypeEvaluator.getResolveResultsFromQualifier(TypeScriptTypeEvaluator.java:585)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$processRefExpr$30(JSTypeEvaluator.java:1439)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluateContext.processExpression(JSEvaluateContext.java:197)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processRefExpr(JSTypeEvaluator.java:1437)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateTypes(JSTypeEvaluator.java:502)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateExpressionOrElementTypes(JSTypeEvaluator.java:158)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$evaluateExpressionOrElementTypes$1(JSTypeEvaluator.java:141)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processWithEvaluationGuard(JSTypeEvaluator.java:2740)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateExpressionOrElementTypes(JSTypeEvaluator.java:141)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:133)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:116)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:32)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:2201)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:466)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptSignatureChooser.resolveFunctions(TypeScriptSignatureChooser.java:566)
	at com.intellij.lang.javascript.editing.JavaScriptInlayParameterHintsProvider.getParameterHints(JavaScriptInlayParameterHintsProvider.java:66)
	at com.intellij.codeInsight.hints.ParameterHintsPass.process(ParameterHintsPass.java:84)
	at com.intellij.codeInsight.hints.ParameterHintsPass.lambda$doCollectInformation$0(ParameterHintsPass.java:76)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
