### ISSUE TITLE
java.lang.NoClassDefFoundError: java/util/function/Consumer

### ISSUE THREAD

**Issue by kgish** [Turbo87/intellij-emberjs#32]
Since updating to the newest release, I get a fatal IDE error which presents the following stack trace:
```
java/util/function/Consumer
java.lang.NoClassDefFoundError: java/util/function/Consumer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:257)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:253)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:222)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:124)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.emberjs.project.EmberProjectComponent$projectOpened$3$1.run(EmberProjectComponent.kt:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
	at com.emberjs.project.EmberProjectComponent$projectOpened$3.run(EmberProjectComponent.kt:65)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.ClassNotFoundException: java.util.function.Consumer PluginClassLoader[com.emberjs, 1.4.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 32 more
```

**Comment by Turbo87** [comment]
Thanks for reporting this. Which JRE do you use for running the IDE? I suspect that this is related to the last release being built with Java 1.8 instead of 1.7 before.

**Comment by kgish** [comment]
As far as I can see, I have not updated Java recently, here is some data that I hope will help.

![ide-internal-errors](https://cloud.githubusercontent.com/assets/79195/12705331/d81d339e-c86f-11e5-9d00-54742024bfa6.png)
![ide-fatal-errors](https://cloud.githubusercontent.com/assets/79195/12705334/de49674c-c86f-11e5-9cc5-94e048def013.png)

```
WebStorm 11.0.3
Build number: WS-143.1559
JRE: 1.7.0_91-b02 amd64
```
```
$ uname -a
Linux 3.16.0-59-generic #79~14.04.1-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
```
```
$ java -XshowSettings:properties -version
Property settings:
    awt.toolkit = sun.awt.X11.XToolkit
    file.encoding = UTF-8
    file.encoding.pkg = sun.io
    file.separator = /
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.path = .
    java.class.version = 51.0
    java.endorsed.dirs = /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/endorsed
    java.ext.dirs = /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext
        /usr/java/packages/lib/ext
    java.home = /usr/lib/jvm/java-7-openjdk-amd64/jre
    java.io.tmpdir = /tmp
    java.library.path = /usr/java/packages/lib/amd64
        /usr/lib/x86_64-linux-gnu/jni
        /lib/x86_64-linux-gnu
        /usr/lib/x86_64-linux-gnu
        /usr/lib/jni
        /lib
        /usr/lib
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 1.7.0_91-b02
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.7
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.7.0_91
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.7
    java.vm.vendor = Oracle Corporation
    java.vm.version = 24.91-b01
    line.separator = \n 
    os.arch = amd64
    os.name = Linux
    os.version = 3.16.0-59-generic
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.class.path = /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/resources.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/sunrsasign.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jsse.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jce.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/charsets.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rhino.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jfr.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/classes
    sun.boot.library.path = /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64
    sun.cpu.endian = little
    sun.cpu.isalist = 
    sun.desktop = gnome
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = UTF-8
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level = unknown
    user.country = US
    user.dir = /home/kiffin/projects/na-holland/na-holland-ember/public/assets/images
    user.home = /home/kiffin
    user.language = en
    user.name = kiffin
    user.timezone = 

java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
```

**Comment by Turbo87** [comment]
@kgish I've reverted the build process to use JDK 1.7 again and only use JDK 1.8 for the latest EAP snapshot builds where JDK 1.7 is no longer supported. I will release v1.4.1 in the next minutes and hopefully it will work again with that version.

**Comment by kgish** [comment]
Thanks! So do I need to reinstall the plugin as usual or are there other steps i need to take?

Also, is it recommended to upgrade my JDK to a newer version?

**Comment by Turbo87** [comment]
@kgish the IDE should show you that the "Ember.js" plugin can be updated to v1.4.1 and once you've done that and restarted the IDE it should work fine again

**Comment by kgish** [comment]
I can verify that it now works, thanks very much.
