### ISSUE TITLE
Instant crash on IntelliJ IDEA 2020.3

### ISSUE THREAD

**Issue by ofry** [Turbo87/intellij-emberjs#353]
### Steps to Reproduce

Just launch IntelliJ IDEA, maybe, with PHP composer project loaded.

**Expected behavior:** Plugin should NOT crash.

**Actual behavior:** 

```
Error while indexing /home/ofry/.local/share/JetBrains/IntelliJIdea2020.3/php/lib/php.jar!/stubs/xmlwriter/xmlwriter.php
To reindex this file IDEA has to be restarted

com.intellij.util.indexing.impl.MapReduceIndex$MapInputException: Failed to map data for input 8174 for index php.unit.covers
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:232)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.updateBaseIndex(MergedInvertedIndex.java:324)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.mapInputAndPrepareUpdate(MergedInvertedIndex.java:112)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.mapInputAndPrepareUpdate(MergedInvertedIndex.java:38)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1474)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1356)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:555)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1326)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1253)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexOneFileOfJob$2(IndexUpdateRunner.java:251)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:422)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:186)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileOfJob(IndexUpdateRunner.java:254)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexJobsFairly$1(IndexUpdateRunner.java:196)
	at com.intellij.openapi.progress.impl.ProgressSuspender.executeNonSuspendableSection(ProgressSuspender.java:83)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexJobsFairly(IndexUpdateRunner.java:199)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$doIndexFiles$0(IndexUpdateRunner.java:133)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: containingFile.originalFile.virtualFile must not be null
	at com.emberjs.utils.PsiElementExtensionsKt.getOriginalVirtualFile(PsiElementExtensions.kt:16)
	at com.emberjs.navigation.EmberTestFinder.isTest(EmberTestFinder.kt:55)
	at com.intellij.testIntegration.TestFinderHelper.isTest(TestFinderHelper.java:44)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpUnitCoversIndex$1.map(PhpUnitCoversIndex.java:62)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpUnitCoversIndex$1.map(PhpUnitCoversIndex.java:53)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:291)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:283)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:168)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:46)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:226)
	... 44 more
```

**Reproduces how often:** Every launch.

### Versions
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on December 1, 2020
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-32-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1466M
Cores: 4
Registry: vcs.annotations.preload=true
Non-Bundled Plugins: Quick Patch, bundled-intellij-idea-help, com.dmitryzhelnin.intellij.plugin.gitextensions, com.intellij.apacheConfig, com.jetbrains.annotations.preloader, com.jetbrains.plugins.ini4idea, GitCheckoutFilesFromOtherBranch, com.vladsch.git-file-case-fixer, uk.co.ben-gibson.remote.repository.mapper, com.atlassian.bitbucket.references, org.turbanov.commits.message.checker, LogSupport2, String Manipulation, com.euphoricity.gitignore, biz.elfuego.idea.issues.gitea, com.emberjs, com.fedot.idea.requirejs, org.igu.plugins.consolelog, Dart, org.jetbrains.plugins.vue, com.bruce.intellijplugin.generatesetter, zielu.gittoolbox, org.intellij.scala, com.jetbrains.php, com.bitrixsoft.lang, com.alicannklc.codeigniter.snippets, com.alicannklc.laravel.snippets, com.aurimasniekis.phpclasstemplates, com.aurimasniekis.phppsr4namespacedetector, com.cedricziel.idea.typo3, com.dryabov.phpStorm.phpregexp, com.github.timo_reymann.composer_dump_autoload_phpstorm_plugin, com.github.woru.options-completion-phpstorm-plugin, com.jetbrains.php.blade, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsEA, com.wbars.php.folding, de.espend.idea.php.phpunit, lt.martynassateika.idea.codeigniter, org.endpointdeps.EndpointDependencies, org.mediawiki, pro.opcode.bitrix, ru.vkurdin.idea.php.lambdafolding, com.jetbrains.php.framework, com.jetbrains.php.drupal, org.masamotod.idea.Drupal8NamespaceDetector, com.jetbrains.php.wordPress, com.jetbrains.twig, com.kalessil.phpStorm.yii2inspections, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, de.espend.idea.php.drupal, Pythonid, ru.adelf.idea.dotenv
Current Desktop: KDE

Ember.JS plugin version: 2016.2.4-0

**Comment by Turbo87** [comment]
sorry, but there is no officially supported plugin release for v2020.3 yet
