### ISSUE TITLE
PluginException: Cannot load class com.emberjs.project.EmberProjectStructureDetector

### ISSUE THREAD

**Issue by jiridanek** [Turbo87/intellij-emberjs#362]
### Description

```
com.intellij.diagnostic.PluginException: Cannot load class com.emberjs.project.EmberProjectStructureDetector (
  error: com/intellij/ide/util/projectWizard/importSources/ProjectStructureDetector,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Ember.js, id=com.emberjs, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.4961.33.plugins/Ember.js, version=2016.2.4-0, package=null), packagePrefix=null, instanceId=107, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:324)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:221)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1090)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:712)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.java:25)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:64)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:502)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:436)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:268)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:38)
	at com.intellij.ide.util.projectWizard.importSources.JavaSourceRootDetectionUtil.suggestRoots(JavaSourceRootDetectionUtil.java:34)
	at org.jetbrains.idea.maven.importing.MavenFoldersImporter.configGeneratedSourceFolder(MavenFoldersImporter.java:371)
	at org.jetbrains.idea.maven.importing.MavenFoldersImporter.configGeneratedFolders(MavenFoldersImporter.java:250)
	at org.jetbrains.idea.maven.importing.MavenFoldersImporter.config(MavenFoldersImporter.java:93)
	at org.jetbrains.idea.maven.importing.MavenFoldersImporter.config(MavenFoldersImporter.java:82)
	at org.jetbrains.idea.maven.importing.MavenModuleImporter.configFolders(MavenModuleImporter.java:196)
	at org.jetbrains.idea.maven.importing.MavenModuleImporter.config(MavenModuleImporter.java:93)
	at org.jetbrains.idea.maven.importing.MavenProjectImporter.importModules(MavenProjectImporter.java:578)
	at org.jetbrains.idea.maven.importing.MavenProjectImporter.importProjectOldWay(MavenProjectImporter.java:232)
	at org.jetbrains.idea.maven.importing.MavenProjectImporter.importProject(MavenProjectImporter.java:106)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.lambda$importProjects$22(MavenProjectsManager.java:1267)
	at org.jetbrains.idea.maven.project.MavenProjectsManager$10.run(MavenProjectsManager.java:1278)
	at org.jetbrains.idea.maven.utils.MavenUtil.lambda$runInBackground$6(MavenUtil.java:521)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/intellij/ide/util/projectWizard/importSources/ProjectStructureDetector
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:255)
	at com.intellij.util.lang.JdkZipResourceFile.findClass(JdkZipResourceFile.java:148)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:55)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:241)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:188)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:316)
	... 34 more
Caused by: java.lang.ClassNotFoundException: com.intellij.ide.util.projectWizard.importSources.ProjectStructureDetector PluginClassLoader(plugin=PluginDescriptor(name=Ember.js, id=com.emberjs, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.4961.33.plugins/Ember.js, version=2016.2.4-0, package=null), packagePrefix=null, instanceId=107, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:205)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 42 more
```

### Steps to Reproduce

Instal the EAP version of IntelliJ, use the IDE for a while. This pops up.

### Versions

- The first two lines of the `Help` -> `About` output:

IntelliJ IDEA 2021.1 EAP (Ultimate Edition)
Build #IU-211.4961.33, built on January 28, 2021

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`):

2016.2.4-0

**Comment by Turbo87** [comment]
2016.2.4-0 is a very old version, that does not support IntelliJ 2021.1. Support for this IntelliJ version is still work-in-progress here.
