### ISSUE TITLE
Worker exited due to exception: it.virtualFile must not be null

### ISSUE THREAD

**Issue by zoltan-nz** [Turbo87/intellij-emberjs#37]
I use the latest Webstorm EAP. It drops this error. Maybe it helps.

WebStorm WS-144.3891.13
Build #WS-144.3891, built on February 10, 2016
JRE: 1.8.0_40-release-b128 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

```
Worker exited due to exception: it.virtualFile must not be null
java.lang.IllegalStateException: it.virtualFile must not be null
	at com.emberjs.icons.EmberIconProvider.getIcon(EmberIconProvider.kt:20)
	at com.emberjs.icons.EmberIconProvider.getIcon(EmberIconProvider.kt:18)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.access$000(ElementBase.java:51)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:62)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:55)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:287)
	at com.intellij.ui.DeferredIconImpl$2$1$1.run(DeferredIconImpl.java:158)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:122)
	at com.intellij.ui.DeferredIconImpl$2$1.run(DeferredIconImpl.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$2.run(ProgressIndicatorUtils.java:80)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$5.run(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:102)
	at com.intellij.ui.DeferredIconImpl$2.run(DeferredIconImpl.java:152)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



java.lang.IllegalStateException: it.virtualFile must not be null
	at com.emberjs.icons.EmberIconProvider.getIcon(EmberIconProvider.kt:20)
	at com.emberjs.icons.EmberIconProvider.getIcon(EmberIconProvider.kt:18)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.access$000(ElementBase.java:51)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:62)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:55)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:287)
	at com.intellij.ui.DeferredIconImpl$2$1$1.run(DeferredIconImpl.java:158)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:122)
	at com.intellij.ui.DeferredIconImpl$2$1.run(DeferredIconImpl.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$2.run(ProgressIndicatorUtils.java:80)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$5.run(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:102)
	at com.intellij.ui.DeferredIconImpl$2.run(DeferredIconImpl.java:152)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



java.lang.IllegalStateException: it.virtualFile must not be null
	at com.emberjs.icons.EmberIconProvider.getIcon(EmberIconProvider.kt:20)
	at com.emberjs.icons.EmberIconProvider.getIcon(EmberIconProvider.kt:18)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.access$000(ElementBase.java:51)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:62)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:55)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:287)
	at com.intellij.ui.DeferredIconImpl$2$1$1.run(DeferredIconImpl.java:158)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:122)
	at com.intellij.ui.DeferredIconImpl$2$1.run(DeferredIconImpl.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$2.run(ProgressIndicatorUtils.java:80)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$5.run(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:102)
	at com.intellij.ui.DeferredIconImpl$2.run(DeferredIconImpl.java:152)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



java.lang.IllegalStateException: it.virtualFile must not be null
	at com.emberjs.icons.EmberIconProvider.getIcon(EmberIconProvider.kt:20)
	at com.emberjs.icons.EmberIconProvider.getIcon(EmberIconProvider.kt:18)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.access$000(ElementBase.java:51)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:62)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:55)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:287)
	at com.intellij.ui.DeferredIconImpl$2$1$1.run(DeferredIconImpl.java:158)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:122)
	at com.intellij.ui.DeferredIconImpl$2$1.run(DeferredIconImpl.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$2.run(ProgressIndicatorUtils.java:80)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$5.run(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:102)
	at com.intellij.ui.DeferredIconImpl$2.run(DeferredIconImpl.java:152)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Turbo87** [comment]
ouch, that certainly shouldn't happen... :wink:

**Comment by Turbo87** [comment]
@zoltan-nz **when** did this happen? did you do anything or does it happen directly on startup?

**Comment by zoltan-nz** [comment]
@Turbo87 you can reproduce this issue if you open an Ember.js project, choose a file, for example `router.js` and start typing any classname or name what you imported in the top of that file, for example: "Em" or "con"

**Comment by Turbo87** [comment]
I see, thanks for the feedback

**Comment by Turbo87** [comment]
@zoltan-nz I think in https://github.com/Turbo87/intellij-emberjs/blob/master/src/main/kotlin/com/emberjs/icons/EmberIconProvider.kt#L20:

```kotlin
fun getIcon(psiFile: PsiFile?) = psiFile?.let { getIcon(it.virtualFile) }
```
needs to be changed to:
```kotlin
fun getIcon(psiFile: PsiFile?) = psiFile?.virtualFile?.let { getIcon(it) }
```

could you try if that works for you?

**Comment by zoltan-nz** [comment]
@Turbo87 Perfect. I updated that line as you suggested, I built the plugin and imported in the latest Webstorm EAP. No exception anymore when I type "Em"... Thank you! :)

**Comment by Turbo87** [comment]
cool, would you mind opening a PR?

**Comment by zoltan-nz** [comment]
Yes, I will do tonight. Cheers. :)

**Comment by mahmoudimus** [comment]
Nice :) :+1: @Turbo87, when were you planning on cutting a release?

**Comment by Turbo87** [comment]
oh, sorry, forgot that. should be published by the end of the day.
