### ISSUE TITLE
InvalidVirtualFileAccessException

### ISSUE THREAD

**Issue by Turbo87** [Turbo87/intellij-emberjs#68]
```
Accessing invalid virtual file: file:///Users/tbn/Code/.../lib/ember-cli-rollup; original:2128483; found:-
com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file:///Users/tbn/Code/.../lib/ember-cli-rollup; original:2128483; found:-
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.a(VirtualDirectoryImpl.java:144)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.a(VirtualDirectoryImpl.java:92)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:396)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:58)
    at com.intellij.openapi.vfs.VirtualFile.findFileByRelativePath(VirtualFile.java:370)
    at com.emberjs.resolver.EmberResolver.find(EmberResolver.kt:50)
    at com.emberjs.resolver.EmberResolver.findIf(EmberResolver.kt:52)
    at com.emberjs.resolver.EmberResolver.resolveNonTestForExtension(EmberResolver.kt:35)
    at com.emberjs.resolver.EmberResolver.resolveNonTest(EmberResolver.kt:28)
    at com.emberjs.resolver.EmberResolver.resolve(EmberResolver.kt:18)
    at com.emberjs.resolver.EmberResolver.resolve(EmberResolver.kt:9)
    at com.emberjs.psi.EmberJSLiteralReference$resolve$1$1$1.invoke(EmberJSLiteralReference.kt:50)
    at com.emberjs.psi.EmberJSLiteralReference$resolve$1$1$1.invoke(EmberJSLiteralReference.kt:22)
    at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:137)
    at kotlin.sequences.DistinctIterator.computeNext(Sequences.kt:484)
    at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:37)
    at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:25)
    at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:242)
    at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:229)
    at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:233)
    at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:229)
    at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
    at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
    at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:141)
    at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
    at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
    at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:527)
    at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:551)
    at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:544)
    at com.emberjs.psi.EmberJSLiteralReference.resolve(EmberJSLiteralReference.kt:59)
    at com.emberjs.psi.EmberJSLiteralReference.multiResolve(EmberJSLiteralReference.kt:32)
    at com.intellij.lang.javascript.inspections.JSUnusedLocalSymbolsInspection$1.visitJSLiteralExpression(JSUnusedLocalSymbolsInspection.java:140)
    at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.accept(JSLiteralExpressionImpl.java:103)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:310)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Turbo87** [comment]
Hasn't happened ever since...

**Comment by G-Rath** [comment]
I've had this happen consistently after running an `npm update`:

```
In file: LightVirtualFile: \EventServiceProvider.php

com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file://C:/Users/G-Rath/workspace/projects-ackama/relm-app/node_modules/.staging/@material-ui/icons-b9c8ddd9; original:464474; found:-; File.exists()=false
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.handleInvalidDirectory(VirtualDirectoryImpl.java:190)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:112)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:78)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:477)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:45)
	at com.emberjs.utils.VirtualFileExtensionsKt.getParentModule(VirtualFileExtensions.kt:34)
	at com.emberjs.utils.VirtualFileExtensionsKt.getParentEmberModule(VirtualFileExtensions.kt:41)
	at com.emberjs.resolver.EmberName$Companion.from(EmberName.kt:56)
	at com.emberjs.index.EmberNameIndex$getIndexer$1.map(EmberNameIndex.kt:23)
	at com.emberjs.index.EmberNameIndex$getIndexer$1.map(EmberNameIndex.kt:13)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:317)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:150)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:40)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:267)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:239)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1253)
	at com.intellij.util.indexing.FileBasedIndexImpl.scheduleFileForIndexing(FileBasedIndexImpl.java:1431)
	at com.intellij.util.indexing.ChangedFilesCollector.lambda$null$2(ChangedFilesCollector.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:188)
	at com.intellij.util.indexing.ChangedFilesCollector.lambda$null$3(ChangedFilesCollector.java:239)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:231)
	at com.intellij.util.indexing.ChangedFilesCollector.lambda$processFilesInReadAction$4(ChangedFilesCollector.java:237)
	at com.intellij.util.indexing.VfsEventsMerger.processChanges(VfsEventsMerger.java:95)
	at com.intellij.util.indexing.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:236)
	at com.intellij.util.indexing.ChangedFilesCollector.ensureUpToDate(ChangedFilesCollector.java:181)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:652)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:540)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:396)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:107)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:95)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:827)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:802)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:877)
	at com.jetbrains.php.PhpIndexImpl.getInterfacesByFQN(PhpIndexImpl.java:898)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveGlobal(ClassReferenceImpl.java:126)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveGlobal(ClassReferenceImpl.java:75)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.lambda$static$0(PhpReferenceImpl.java:156)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:67)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:152)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:225)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:202)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:152)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:150)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:136)
	at com.jetbrains.php.lang.annotator.PhpAnnotatorVisitor.visitPhpUse(PhpAnnotatorVisitor.java:858)
	at com.jetbrains.php.lang.psi.elements.impl.PhpUseImpl.accept(PhpUseImpl.java:53)
	at com.jetbrains.php.lang.annotator.PhpAnnotator.annotate(PhpAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:129)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:110)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:346)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:286)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:599)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:410)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
