### ISSUE TITLE
IOException in YesThread after new EmberJS file action

### ISSUE THREAD

**Issue by panthony** [Turbo87/intellij-emberjs#9]
When I create a new EmberJS file I end up with the following error:

```
Stream closed
java.io.IOException: Stream closed
    at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
    at java.io.OutputStream.write(OutputStream.java:116)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
    at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
    at com.emberjs.cli.YesThread.run(YesThread.kt:13)
```

The files are properly generated.

**Comment by Turbo87** [comment]
as mentioned in #8 this should be a rather easy fix. https://github.com/Turbo87/intellij-emberjs/blob/master/src/main/kotlin/com/emberjs/cli/YesThread.kt#L11-L14 needs to be surrounded by a try-catch with a `break` in the catch block.
